In [1]:
import numpy as np
import numpy.random as rd
import pylab as pl

In [19]:
def generate_sbm_2(n1, n2, block_matrix):
    n = n1 + n2
    adj_matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if i < n1:
                if j < n1:
                    adj_matrix[i, j] = rd.binomial(1, block_matrix[0, 0])
                else:
                    adj_matrix[i, j] = rd.binomial(1, block_matrix[0, 1])
            else:
                if j < n1:
                    adj_matrix[i, j] = rd.binomial(1, block_matrix[1, 0])
                else:
                    adj_matrix[i, j] = rd.binomial(1, block_matrix[1, 1])
    return adj_matrix

In [23]:
m = np.array([[0.8, 0.3], [0.3, 0.8]])
print(generate_sbm_2(5, 5, m))

[[1. 1. 1. 1. 1. 0. 0. 0. 1. 0.]
 [1. 1. 1. 1. 0. 1. 0. 0. 1. 1.]
 [1. 1. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 1. 0. 0. 1. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 1. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]]
