In [1]:
import numpy as np
import numpy.random as rd
import pylab as pl

In [27]:
def generate_sbm_2(n1, n2, block_matrix):
    n = n1 + n2
    adj_matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(i, n):
            if i < n1:
                if j < n1:
                    adj_matrix[i, j] = rd.binomial(1, block_matrix[0, 0])
                    adj_matrix[j, i] = adj_matrix[i, j]
                else:
                    adj_matrix[i, j] = rd.binomial(1, block_matrix[0, 1])
                    adj_matrix[j, i] = adj_matrix[i, j]
            else:
                if j < n1:
                    adj_matrix[i, j] = rd.binomial(1, block_matrix[1, 0])
                    adj_matrix[j, i] = adj_matrix[i, j]
                else:
                    adj_matrix[i, j] = rd.binomial(1, block_matrix[1, 1])
                    adj_matrix[j, i] = adj_matrix[i, j]
    return adj_matrix

def is_symmetric(m, n):
    for i in range(n):
        for j in range(n):
            if m[i, j] != m[j, i]:
                return False
    return True

In [30]:
m = np.array([[0.8, 0.3], [0.3, 0.8]])
sbm_matrix = generate_sbm_2(5, 5, m)
print(sbm_matrix)
print(is_symmetric(sbm_matrix, 10))

[[1. 1. 1. 0. 1. 0. 0. 1. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 1. 0. 0.]
 [1. 1. 1. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 1. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 0. 1. 1.]]
True
